### PR TITLE
Unexepected method calls cause subsequent verification to fail.

### PR DESCRIPTION
**Pull request by arykov**
This is in reference to http://jira.codehaus.org/browse/EASYMOCK-150
that is now migrated here https://github.com/henri-tremblay/mytest/issues/391

### CODE REVIEW

**Comment by arykov** [comment]
Tests that previously caught AssertionError and relied on successful verify afterwards will fail unless resetUnexpectedCallVerification is called. Thoughts?

**Comment by arykov** [comment]
Are you intending to integrate it or close?

**Comment by henri-tremblay** [comment]
I just looked at it. If I integrate it, it will be soon. Two questions: What is the real use-case? By that I mean, if you don't care about expectations, why not using a nice mock? And why can't you register the required expectations?

I'm just trying to understand the original requirement. What was attempted and failed.

**Comment by arykov** [comment]
[This is our original discussion on the subject](https://github.com/henri-tremblay/mytest/issues/391)

**Comment by henri-tremblay** [comment]
Thank you very much for the link. Indeed, that was a bit far in my head (since the issue is quite old... my fault here).

So please let me look back to it but it should be in one flavour or another in version 3.5

**Comment by henri-tremblay** [comment]
Thanks a lot for the bug report and PR. I fixed it in a different way so I won't use the PR directly.

**Pull request closed without merging**
